### ISSUE TITLE
CMake Error at cmake/find_ncine.cmake:4

### ISSUE THREAD

**Issue by Dzlua** [nCine/ncTemplate#1]
E:\downloads\ncTemplate-master\build>cmake ..
ncTemplate by Angelo Theodorou
A template project for applications and games made with the nCine
https://ncine.github.io
Copyright ©2019-2020 Angelo Theodorou

-- Selecting Windows SDK version 10.0.17763.0 to target Windows 10.0.18362.
CMake Error at cmake/find_ncine.cmake:4 (find_package):
  Could not find a configuration file for package "nCine" that is compatible
  with requested version "".

  The following configuration files were considered but not accepted:

    C:/Program Files/nCine/cmake/nCineConfig.cmake, version: 2019.10 (64bit)

Call Stack (most recent call first):
  CMakeLists.txt:17 (include)

-- Configuring incomplete, errors occurred!
See also "E:/downloads/ncTemplate-master/build/CMakeFiles/CMakeOutput.log".

system：win10x64  1909
nCline：nCine-2019.10-Win64-VS2017.exe
install path：C:\Program Files\nCine

**Comment by Dzlua** [comment]
with cmake gui
config cmake generator：x64
Solved

**Comment by encelo** [comment]
It is possible to use CMake from the command line by specifying the generator and the platform, for example:
`cmake -S ncTemplate -B ncTemplate-build -G "Visual Studio 16 2019" -A x64`

Have also a look at https://ncine.github.io/build-windows/ and join us on [Discord](https://discord.gg/495ab6Y). :)
